# Generated by Django 5.2 on 2025-09-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
    ]
